### PR TITLE
Handle bind (=?) errors in `without` statements differently

### LINKED ISSUE #53: Binding error - Attempt to read from nil
Tested on nim `1.6.14`

Happens within procs that have a type param and that are called by one of imports within `without` macro

main.nim
```nim
import ./somefn
import ./otherfn

discard int.someFn()
```

somefn.nim
```nim
import pkg/questionable
import pkg/questionable/results

proc someFn*(
  X: type int
): ?!int =
  let res = success(1)

  if err =? res.errorOption:
    echo "err" & err.msg
  else:
    echo "no err"

  failure("")
```

otherfn.nim
```nim
import pkg/questionable
import pkg/questionable/results

import ./somefn

proc otherFn*(): void =
  without x =? int.someFn(), err:
    echo "was err" & err.msg
```

If we run `nim c -r main.nim` we get:
```
Traceback (most recent call last)
/Users/tbekas/Workspace/nim-codex/main.nim(8) main
/Users/tbekas/Workspace/nim-codex/vendor/questionable/questionable/private/binderror.nim(24) someFn
/Users/tbekas/Workspace/nim-codex/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(302) unsureAsgnRef
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/Users/tbekas/Workspace/nim-codex/main '
```

### PR DESCRIPTION
**Pull request by markspanbroek**
Keeps track of the current error variable at compile time, instead of using a pointer to the error variable at runtime.

~~Employs a trick with an unused type parameter to ensure that invocations of the bindFailed() macro are expanded after captureBindError() is expanded.~~

Fixes #53

### CODE REVIEW

**Review by tbekas — APPROVED** [review]
Thanks for fixing this! LGTM 👌

**Comment by elcritch** [comment]
Oopps I missed this! I'll give it a review now.

**Comment by markspanbroek** [comment]
Did you get around to reviewing this @elcritch? Would love to hear your opinion on this if you have the time.

**Comment by elcritch** [comment]
> Did you get around to reviewing this @elcritch? Would love to hear your opinion on this if you have the time.

I started reviewing it but got interrupted. I'll review it again now.

File: questionable/private/binderror.nim [hunk 1]
```diff
@@ -1,24 +1,43 @@
 import std/options
+import std/macros
 
-var captures {.global, compileTime.}: int
-var errorVariable {.threadvar.}: ptr ref CatchableError
+# A stack of names of error variables. Keeps track of the error variables that
+# are given to captureBindError().
+var errorVariableNames {.global, compileTime.}: seq[string]
```
Comment (elcritch) [inline questionable/private/binderror.nim:6]: I like this scheme better than the global var. Hopefully it isolates the error variables better too.

File: questionable/private/binderror.nim [hunk 2]
```diff
@@ -1,24 +1,43 @@
...
 
-  static: inc captures
-  let evaluated = expression
-  static: dec captures
-
-  errorVariable = previousErrorVariable
-
-  evaluated
+  # name of the error variable as a string literal
+  let errorVariableName = newLit($error)
```
Comment (elcritch) [inline questionable/private/binderror.nim:13]: How the name generation here is working isn't quite clear to me. Looks like it's from:

```nim
  quote do:
    var error: ref CatchableError
    without captureBindError(error, `condition`):
```

The `var error` here becomes a genSym name right?

File: questionable/private/binderror.nim [hunk 3]
```diff
@@ -1,24 +1,43 @@
...
-  when captures > 0:
-    mixin error
-    errorVariable[] = expression.error
+macro bindFailed*(expression: typed) =
+  ## Called when a binding (=?) fails.
+  ## Assigns an error to the error variable (specified in captureBindError())
+  ## when appropriate.
+
+  # The `expression` parameter is typed to ensure that the compiler does not
+  # expand bindFailed() before it expands invocations of captureBindError().
```
Comment (elcritch) [inline questionable/private/binderror.nim:33]: Ah, nice solution.

**Review by elcritch — APPROVED** [review]

File: questionable/private/binderror.nim (hunk 2 above)
Comment (markspanbroek) [reply questionable/private/binderror.nim:13]: Yes, that's correct. I can make that more explicit by adding a {.gensym.} pragma.

**Comment by elcritch** [comment]
Nice, I like removing the global error variable. I've also run into segfault issues lately with threadvars and clang. This approach might even help performance a bit by localizing the error variable on the stack.
